#!/usr/bin/env ruby

require 'sinatra'

host = "localhost"
port = 7000

configure do
  set :bind, host
  set :port, port
end

# Use HTTP Basic Rack middleware, which will apply HTTP Basic 
# authentication to *all* requests.
# Normally this is where you would validate the username and password
# against a database or directory, but as this is a test IdP it can use
# anything.
use Rack::Auth::Basic do |username, password|
  true # accept anything
end

# Single route for matching a single sign-on request
get '/saml/sso' do
  saml_request = params['SAMLRequest']
  relay_state = params['RelayState']
end

